require "user.plugins"
require "user.options"
require "user.colorscheme"
require "user.whichkey"
require "user.bufferline"
require "user.lualine"
require "user.indentline"
require "user.keymaps"
require "user.nvim-tree"
require "user.toggleterm"
-- require "user.comment"
require "user.cmp"
require "user.lsp"
require "user.alpha"
require "user.project"
require "user.telescope"
require "user.treesitter"
require "user.gitsigns"
